server:
  port: 8081
spring:
  application:
    name: jmxm
  datasource:
    url: jdbc:mysql://39.104.23.216:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ant-storm
    password: X2AmjZsaNt25r2Sn
    #数据库连接池
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      max-lifetime: 30000
    primary:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  mvc:
    static-path-pattern: /imgs/**
  resources:
    static-locations: /home/cc/frontend/zxImgs/

  #此项配置是用来忽略不同的bean的同名异常的  不配置默认为true
  #true为忽视。false为不忽视编译会报错
  main:
    allow-bean-definition-overriding: true
  #此配置是配置前端上传文件的最大值
  servlet:
    multipart:
      max-file-size: 50MB
