server:
  potr: 8081
spring:
  application:
    name: jmxm
  datasource:
    url: jdbc:mysql://111.229.243.156:3306/jcxm?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://111.229.243.156:3306/jmxm_test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: cc
    password: Syt520!@#$%$$####$$$
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      max-lifetime: 30000
    primary:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  mvc:
    static-path-pattern: /imgs/**
  resources:
    static-locations: /home/cc/frontend/zxImgs/
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
    max-file-size: 50MB
logging:
 level:
  com.cn.jc.jmxm.mapper: debug
redis:
  # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
  database: 3
  # redis服务器地址（默认为loaclhost）
  host: 111.229.243.156
  # redis端口（默认为6379）
  post: 6379
  # redis访问密码（默认为空）
  password: ccpass9527
  # redis连接超时时间（单位毫秒）
  timeout: 0
  # redis连接池配置
  pool:
    # 最大可用连接数（默认为8，负数表示无限）
    max-active: 8
    # 最大空闲连接数（默认为8，负数表示无限）
    max-idle: 8
    # 最小空闲连接数（默认为0，该值只有为正数才有用）
    min-idle: 0
    # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
    max-wait: -1